/*
Proyecto: Ahorcado.py
Autor: Juan Pena
Descripcion: Script para poblar la base de datos
Fecha: 27/07/2024
*/

-- Poblado de la tabla de categoria

INSERT INTO categoria (id, nombre) VALUES (1, 'Animales');
INSERT INTO categoria (id, nombre) VALUES (2, 'Paises');
INSERT INTO categoria (id, nombre) VALUES (3, 'Deportes');
INSERT INTO categoria (id, nombre) VALUES (4, 'Colores');
INSERT INTO categoria (id, nombre) VALUES (5, 'Instrumentos musicales');
INSERT INTO categoria (id, nombre) VALUES (6, 'Profesiones');
INSERT INTO categoria (id, nombre) VALUES (7, 'Cuerpo humano');
INSERT INTO categoria (id, nombre) VALUES (8, 'Transportes');
INSERT INTO categoria (id, nombre) VALUES (9, 'Comida');
INSERT INTO categoria (id, nombre) VALUES (10, 'Herramientas');
INSERT INTO categoria (id, nombre) VALUES (11, 'Objetos');
INSERT INTO categoria (id, nombre) VALUES (12, 'Marcas');

-- Poblado de la tabla de palabras

INSERT INTO palabra (id, nombre, categoria_id) VALUES (1, 'Perro', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (2, 'Gato', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (3, 'Elefante', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (4, 'Leon', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (5, 'Tigre', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (6, 'Jirafa', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (7, 'Cebra', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (8, 'Canguro', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (9, 'Koala', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (10, 'Panda', 1);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (11, 'Rusia', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (12, 'Espana', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (13, 'Francia', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (14, 'Alemania', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (15, 'Italia', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (16, 'Argentina', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (17, 'Brasil', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (18, 'Mexico', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (19, 'Colombia', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (20, 'Chile', 2);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (21, 'Futbol', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (22, 'Baloncesto', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (23, 'Tenis', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (24, 'Natacion', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (25, 'Atletismo', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (26, 'Voleibol', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (27, 'Golf', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (28, 'Rugby', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (29, 'Ciclismo', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (30, 'Boxeo', 3);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (31, 'Rojo', 4);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (32, 'Azul', 4);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (33, 'Verde', 4);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (34, 'Amarillo', 4);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (35, 'Blanco', 4);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (36, 'Negro', 4);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (37, 'Morado', 4);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (38, 'Violin', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (39, 'Piano', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (40, 'Guitarra', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (41, 'Bateria', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (42, 'Trompeta', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (43, 'Saxofon', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (44, 'Violonchelo', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (45, 'Flauta', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (46, 'Trombon', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (47, 'Clarinete', 5);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (48, 'Medico', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (49, 'Ingeniero', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (50, 'Abogado', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (51, 'Profesor', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (52, 'Cocinero', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (53, 'Musico', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (54, 'Policia', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (55, 'Bombero', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (56, 'Arquitecto', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (57, 'Piloto', 6);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (58, 'Cabeza', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (59, 'Brazo', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (60, 'Pierna', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (61, 'Ojo', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (62, 'Nariz', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (63, 'Boca', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (64, 'Oreja', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (65, 'Mano', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (66, 'Pie', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (67, 'Corazon', 7);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (68, 'Avion', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (69, 'Coche', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (70, 'Barco', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (71, 'Tren', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (72, 'Bicicleta', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (73, 'Helicoptero', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (74, 'Motocicleta', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (75, 'Camion', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (76, 'Autobus', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (77, 'Taxis', 8);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (78, 'Pizza', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (79, 'Hamburguesa', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (80, 'Sushi', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (81, 'Pasta', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (82, 'Ensalada', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (83, 'Tacos', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (84, 'Sopa', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (85, 'Arroz', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (86, 'Pollo', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (87, 'Pescado', 9);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (88, 'Martillo', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (89, 'Destornillador', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (90, 'Llave inglesa', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (91, 'Sierra', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (92, 'Taladro', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (93, 'Alicate', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (94, 'Cinta metrica', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (95, 'Tijeras', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (96, 'Pincel', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (97, 'Destapador', 10);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (98, 'Mesa', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (99, 'Silla', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (100, 'Lampara', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (101, 'Cama', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (102, 'Sofa', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (103, 'Mesa de centro', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (104, 'Armario', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (105, 'Estanteria', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (106, 'Escritorio', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (107, 'Television', 11);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (108, 'Nike', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (109, 'Adidas', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (110, 'Apple', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (111, 'Samsung', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (112, 'Microsoft', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (113, 'Coca-Cola', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (114, 'Toyota', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (115, 'Amazon', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (116, 'Facebook', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (117, 'Netflix', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (118, 'Instagram', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (119, 'Twitter', 12);
INSERT INTO palabra (id, nombre, categoria_id) VALUES (120, 'WhatsApp', 12);
